<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>DeskWall.Designer</AssemblyName>
    <RootNamespace>DeskWall.Designer</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <IsAotCompatible>false</IsAotCompatible>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.*" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeskWall.Core\DeskWall.Core.csproj" />
  </ItemGroup>
</Project>
